
services:
  calibre-web-automated-book-downloader:
    # Вместо готового образа используем сборку из твоего форка
    build: .
    container_name: calibre-web-automated-book-downloader
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: ru
      USE_BOOK_TITLE: true
      TZ: Europe/Moscow
      APP_ENV: prod
      UID: 1000
      GID: 100
      MAX_CONCURRENT_DOWNLOADS: 3
      DOWNLOAD_PROGRESS_UPDATE_INTERVAL: 5
      # Если вынесешь URL inpx-web в config.py:
      # INPX_WEB_URL: http://192.168.31.216:12380/opds
    ports:
      - "8084:8084"
    restart: unless-stopped
    volumes:
      # Папка для загруженных книг
      - /media/qbit/downloads/books:/cwa-book-ingest
      # Если используешь авторизацию через Calibre-Web:
      # - /cwa/config/path/app.db:/auth/app.db:ro
